name: Build Image

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    types:
      - completed
    branches:
      - main
      - staging
      - development
  workflow_dispatch:

jobs:
  build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "note-app-demo-flask-api-backend-${GITHUB_REF#refs/*/}:$(date +%s)"