name: Build Image

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' || github.ref_name == 'development' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the Docker image
        env:
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          DEBUG: ${{ secrets.DEBUG }}
          PORT: ${{ secrets.PORT }}
          
        run: |
          docker build . \
          --build-arg FLASK_ENV="$FLASK_ENV" \
          --build-arg DEBUG="$DEBUG" \
          --build-arg PORT="$PORT" \
          --tag "note-app-demo-flask-api-backend-${GITHUB_REF#refs/*/}:$(date +%s)"