name: CI Workflow

on:
  push:
    branches-ignore:
      - 'docs/**'

jobs:
  run-linter:
    uses: ./.github/workflows/linter.yaml

  run-tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      FLASK_ENV: ${{ secrets.TEST_FLASK_ENV }}
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  build-image:
    needs: [run-linter,run-tests]
    uses: ./.github/workflows/build.yaml

  publish-image:
    needs: build-image
    uses: ./.github/workflows/publish.yaml