name: CI Workflow

on:
  push:
    branches-ignore:
      - 'docs/**'

jobs:
  run-linter:
    uses: ./.github/workflows/linter.yaml

  run-tests:
    needs: run-linter
    uses: ./.github/workflows/tests.yaml
    with:
      environment: testing

  build-image:
    needs: run-tests
    uses: ./.github/workflows/build.yaml

  publish-image:
    needs: build-image
    uses: ./.github/workflows/publish.yaml