name: CI Workflow

on:
  push:
    branches-ignore:
      - 'docs/**'

jobs:
  run-linter:
    uses: ./.github/workflows/linter.yaml

  run-tests:
    uses: ./.github/workflows/tests.yaml
    with:
      environment: testing

  build-image:
    needs: [run-linter,run-tests]
    uses: ./.github/workflows/build.yaml

  publish-image:
    needs: build-image
    uses: ./.github/workflows/publish.yaml