name: CI Workflow

on:
  push:
    branches-ignore:
      - 'docs/**'

jobs:
  linter:
    uses: ./.github/workflows/linter.yaml

  tests:
    needs: linter
    uses: ./.github/workflows/tests.yaml

  build:
    needs: tests
    uses: ./.github/workflows/build.yaml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yaml