name: CI Workflow

on:
  push:
    branches-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  run-linter:
    uses: ./.github/workflows/linter.yaml

  run-tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      FLASK_ENV: ${{ secrets.TEST_FLASK_ENV }}
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

  build-image:
    needs: [run-linter,run-tests]
    uses: ./.github/workflows/build.yaml

  publish-image-dev:
    needs: build-image
    uses: ./.github/workflows/publish.yaml
    if: ${{ github.ref_name == 'development' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FLASK_ENV: ${{ secrets.DEV_FLASK_ENV }}
      DEBUG: ${{ secrets.NONPROD_DEBUG }}
      PORT: ${{ secrets.FLASK_PORT }}
  
  publish-image-staging:
    needs: build-image
    uses: ./.github/workflows/publish.yaml
    if: ${{ github.ref_name == 'staging' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FLASK_ENV: ${{ secrets.STG_FLASK_ENV }}
      DEBUG: ${{ secrets.NONPROD_DEBUG }}
      PORT: ${{ secrets.FLASK_PORT }}

  publish-image-prod:
    needs: build-image
    uses: ./.github/workflows/publish.yaml
    if: ${{ github.ref_name == 'main' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FLASK_ENV: ${{ secrets.PROD_FLASK_ENV }}
      DEBUG: ${{ secrets.PROD_DEBUG }}
      PORT: ${{ secrets.FLASK_PORT }}