name: Publish Image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      FLASK_ENV:
        required: true
      DEBUG:
        required: true
      PORT:
        required: true
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' || github.ref_name == 'development' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/note-app-demo-flask-api-backend-${{ github.ref_name }}:latest"
          build-args: |
            FLASK_ENV=${{ secrets.FLASK_ENV }}
            DEBUG=${{ secrets.DEBUG }}
            PORT=${{ secrets.PORT }}