name: Run Tests

on:
  workflow_run:
    workflows: [ "Lint Code Base" ]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    environment: "testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        env:
          FLASK_ENV: ${{ var.FLASK_ENV }}
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
          TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          pytest